// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfcLOOs30WuuS93lGQNg-Si2H0GTL--k',
    appId: '1:609195297990:web:9fd2e254fdc170b9995bc7',
    messagingSenderId: '609195297990',
    projectId: 'baby-cradle-ab503',
    authDomain: 'baby-cradle-ab503.firebaseapp.com',
    storageBucket: 'baby-cradle-ab503.appspot.com',
    measurementId: 'G-ZVKF3NKR6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyButbvTWlJayVZyldGi9U3wO36XlB7Xa-A',
    appId: '1:609195297990:android:dc44ec0a915afc77995bc7',
    messagingSenderId: '609195297990',
    projectId: 'baby-cradle-ab503',
    storageBucket: 'baby-cradle-ab503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEXzIMdHN4h20Aoe2Z0S2yINxZgstpWM',
    appId: '1:609195297990:ios:3e83d25ba505be0f995bc7',
    messagingSenderId: '609195297990',
    projectId: 'baby-cradle-ab503',
    storageBucket: 'baby-cradle-ab503.appspot.com',
    iosBundleId: 'com.example.smartBabyCradle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEXzIMdHN4h20Aoe2Z0S2yINxZgstpWM',
    appId: '1:609195297990:ios:4dcc71735835b79e995bc7',
    messagingSenderId: '609195297990',
    projectId: 'baby-cradle-ab503',
    storageBucket: 'baby-cradle-ab503.appspot.com',
    iosBundleId: 'com.example.smartBabyCradle.RunnerTests',
  );
}
